### ISSUE TITLE
800 and 900 are essentially black

### ISSUE THREAD

**Issue by jjozsi** [anheric/tailwindshades#26]
I really like the tool and it's simplicity, it works well for most colours.
Today I used it with a blue shade of #00659B and it gave me back #000102 and #000000 in the last two positions.
I tested it with a few other darker base colours such as #AA0000 and it gave me the same results: last 2 are black (110000 and 000000). A these are not even particularly dark colours, only a bit darker than the normal base colours.

It might come back to what others suggested: the ability to choose the position of the base colour, in my case probably 600. Or, the algorithm could automatically decide if a colour is too dark for 500 and would adjust the palette accordingly.

Thanks for the tool anyway, I hope it helps.

**Comment by leoquack** [comment]
Hi! Thanks for the feedback and I agree, the ability to choose a different base color will be great. Will work on #22 next chance I get.

For the example colors, the algorithm should detect that there is only a tiny room for darker tones, and adjust the lightness accordingly. Same for the light tones, of course. This is something that was bugging me from the start and since my color theory is extremely basic, I wanted to find a good study or code that I could follow to make better default shades.

Of course, you could adjust the sliders to manually fix the shades, for example for #00659B, [this looks good on my screen](https://www.tailwindshades.com/#color=00679E&step-up=11&step-down=8&name=bahama-blue&overrides=eyI5Ijp7Imh1ZSI6LTEsInNhdHVyYXRpb24iOi0xLCJsaWdodG5lc3MiOjQsImhleCI6IjAwMEQxNCIsInRleHRDb2xvciI6IndoaXRlIn0sIjAuNSI6eyJodWUiOi0xLCJzYXR1cmF0aW9uIjotMSwibGlnaHRuZXNzIjo4NC41LCJoZXgiOiJCMEUzRkYiLCJ0ZXh0Q29sb3IiOiJibGFjayJ9fQ%3D%3D), and for #AA0000, I made [this](https://www.tailwindshades.com/#color=AA0000&step-up=12&step-down=9&name=bright-red&overrides=eyI5Ijp7Imh1ZSI6LTEsInNhdHVyYXRpb24iOi0xLCJsaWdodG5lc3MiOjQsImhleCI6IjE0MDAwMCIsInRleHRDb2xvciI6IndoaXRlIn0sIjAuNSI6eyJodWUiOi0xLCJzYXR1cmF0aW9uIjotMSwibGlnaHRuZXNzIjo5Mi4zMzMzMzMzMzMzMzMzMywiaGV4IjoiRkZEOEQ4IiwidGV4dENvbG9yIjoiYmxhY2sifX0%3D). For both, the lightest and darkest shades had their lightness changed (on fine tune on the left). Also changed the step up/ step down sliders on the right.

I will keep this open though until a cool, automatic solution can be found :)

**Comment by jjozsi** [comment]
Thanks, I didn't see those options, I'll play with them next time. Thanks again for the great tool!
